name: Run tests

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      issues: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6
      - name: Go test
        run: make test-go
      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: ./junit/*-report.xml
          report_individual_runs: "true"